[project]
name = "EasyTCR"
version = "0.0.1"
authors = [
  { name="gary", email="gary_dou327@163.com" },
]
description = "Explore TCR repertoire"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
        'numpy>=1.20.2',
        'pandas>=1.2.5',
        'plotnine>=0.8.0',
        'seaborn>=0.12.2',
        'matplotlib>=3.2.2',
        'scipy>=1.5.3'
]
