[tool.poetry]
name = "dare-datasets"
version = "0.1.4"
description = ""
authors = ["MikeXydas <mikexydas@gmail.com>"]
readme = "README.md"
packages = [{include = "dare_datasets"}]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
gdown = "^4.7.1"


[tool.poetry.group.dev.dependencies]
pylint = "^2.17.4"
pytest = "^7.3.1"
mkdocs = "^1.4.3"
mkdocstrings = {extras = ["python"], version = "^0.21.2"}
mkdocs-material = "^9.1.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
