[project]
name = "np_envs"
version = "0.1.5"
description = "Config and scripts for managing virtual envs for Mindscope Neuropixels projects."
authors = [
    { name = "bjhardcastle", email = "ben.hardcastle@alleninstitute.org" },
]
dependencies = [
    "np-config>=0.4.20",
    "np-logging>=0.5.1",
    "np-tools>=0.1.14",
    "importlib-resources>=5.12.0",
    "typer>=0.9.0",
]
requires-python = ">=3.8"
readme = "README.md"

[project.license]
text = "MIT"

[project.scripts]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.scripts.pub]
composite = [
    "pdm bump patch",
    "pdm publish",
]
