[tool.poetry]
name = "anastasia-logging"
version = "1.3.3"
description = "Anastasia Logging Standarization"
authors = ["anastasiaai"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
