# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "motdb"
version = "0.0.4"
description = "Má»™t Database Layer to ... Bind Them (All)"
readme = "README.md"
authors = [{ name = "Mike Steele", email = "mike@mikesteele.us" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["database", "fetch", "db"]
dependencies = [
    'tomli >= 2.0.1',
    'click >= 8.1.3'
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/soulrx/motdb"

[project.scripts]
motdb = "motdb.__main__:main"

[tool.bumpver]
current_version = "0.0.4"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"src/motdb/__init__.py" = ["{version}"]

