[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
dependencies = ["requests",]
name = "keycloak_api_manager"
version = "1.0.1"
authors = [
    {name = "Polyakov Sergey", email = "martinlauren555@gmail.com"},
]
description = "Keycloak API for management"
readme = "README.md"
requires-python = ">=3.5"
keywords = ["keycloak", "API", "keycloak API management"]
license = {text = "MIT License"}
classifiers = [
    "Programming Language :: Python :: 3",
	"License :: OSI Approved :: MIT License",
]
[project.urls]
"Homepage" = "https://github.com/martinlauren55/keycloak-api-manager"
"Documentation" = "https://github.com/martinlauren55/keycloak-api-manager/blob/main/DOCS/DOCS.md"
"Repository" = "https://github.com/martinlauren55/keycloak-api-manager.git"